version: '3'
services:
  # plantuml-service:
  #   image: bitjourney/plantuml-service:1.3.5
  #   ports:
  #     - "1608:1608"
  #   restart: always
  # model-front:
  #   image: nielinjie/quickqui-model-front:latest
  #   depends_on:
  #     - model-server
  #   links:
  #     - model-server
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - PORT=5000
  model-server:
    image: nielinjie/quickqui-model-server:latest
    depends_on:
      - app
    # links:
    #   - plantuml-service
    environment:
      - ENV=dev_docker
    volumes:
      - app-folder:/modelProjectDir
    ports:
      - "1111:1111"
  front:
    image: nielinjie/quickqui-front:latest
    depends_on:
      - app
      - model-server
    links:
      - model-server
    ports:
      - "3000:3000"
    volumes:
      - app-folder:/extendDir
    environment:
      - NODE_ENV=development
      - ENV=dev_docker
      - REACT_APP_ENV=dev_docker
  app:
    image: ${APP_IMAGE}
    volumes: 
      - app-folder:/dir
volumes: 
    app-folder: